# OpenAPI's specification version, not the API's one!
openapi: "3.0.3"

info:
  # The API's name
  title: Postmanaut Directory
  # A markdown compatible description
  description: |
    ![OpenAPI Logo](https://avatars3.githubusercontent.com/u/16343502?v=3&s=100)

    A demo _API_ to **discover** the **_[OpenAPI Specification](https://www.openapis.org/)_**.
  # The version of the API (can be anything as long it's put into a string)
  version: "1.0"

# Where the API is exposed
servers:
  # For now we'll just define a basepath using a relative url
  - description: The base path for all resources 
    url: /postmanaut-directory/v1 

# The resources and operations wil go there
# Leaving it empty to avoid a parsing error
paths: {}
