# Adding search filters (parameters) to Search Postmanauts
openapi: "3.0.3"

info:
  title: Postmanaut Directory
  description: |
    ![OpenAPI Logo](https://avatars3.githubusercontent.com/u/16343502?v=3&s=100)

    A demo _API_ to **discover** the **_[OpenAPI Specification](https://www.openapis.org/)_**.
  version: "1.0"

servers:
  - description: The base path for all resources 
    url: /postmanaut-directory/v1 

paths:
  /postmanauts:
    get:
      summary: Search postmanauts
      description: You can either get the full list of postmanauts or filter them on their name
      # Query (path and header) parameter go here
      parameters:
        - name: name
          in: query
          required: false
          description: Partial or complete postmanaut name
          # Parameters are described using JSON schema too
          schema: 
            type: string
      responses:
        200:
          description: Found postmanauts
          content:
            application/json:
              schema:
                title: Postmanauts
                type: object
                required:
                  - data
                properties:
                  data:
                    type: array
                    minItems: 0
                    items:
                      title: Postmanaut
                      required:
                        - id
                        - name
                        - registrationDate
                      properties:
                        id: 
                          type: string
                        name:
                          type: string
                          minLength: 1
                          maxLength: 256
                        registrationDate:
                          type: string
                          format: date
                        supportLevel:
                          type: string
                          enum:
                            - bronze
                            - silver
                            - gold
                        pendingTickets:
                          type: integer
                          minimum: 0